# tworzymy magazyn słów niechcianych, które usuniemy z ostatecznej bazy (do rozbudowy)
# Modify encoding
Sys.setlocale(category = "LC_ALL", locale = "Polish")
data(stop_words)
stop.words <- data.frame(word=c("ds", "i", "w", "ka", "k", "m", "o", "z", "na", "do", "oraz", "pracy", "masz", "lub", "min", "a", "ms", "od", "lat", "mile", "and", "two", "znajomość", "of", "pracę", 
                                "zakresie", "przy", "jazdy", "klientów", "to", "in", "the", "będzie", "atutem", "praca", "się", "realizacji", "robót", "obsługi", "możliwość", "za", "dodatkowym",
                                "rozwoju", "prac", "tworzeniu", "dla", "ofert", "pomoc", "zapisz", "pracuj", "polityka", "podziel", "oferty", "konto", "cv", "firm", "drukuj", "pan", "pani", "dane",
                                "str", "regulamin", "prywatności", "profile", "prasowe", "pracodawcy", "pracodawców", "porady", "państwa", "with", "data", "urzędy", "szukaj", "zarobki", "kalkulator",
                                "robota.ua", "pana", "danych", "ważna", "plików", "partnerzy", "jeszcze", "główna", "dodaj", "cookies", "archiwum", "2020", "nas", "grupie", "reklama", "umowa", "ważna",
                                "ogłoszenie", "zapisane", "centrum", "itbeta", "firmie", "paź", "przez", "osobowych", "zadań", "wykształcenie", "kreator", "etat", "umiejętność", "pełny", "łódź",
                                "kraków", "jakości", "warszawa", "prawo", "wynagrodzeń", "celu", "dobra", "17", "będą", "jest", "specjalista", "prowadzenie", "your", "prztwarzane", "analiza", "finanse",
                                "stabilne", "raportów", "it", "nie", "bardzo", "2", "on", "związanych", "mid", "regular", "miesiącdo", "zakresu", "work", "przygotowanie", "przetwarzanie", "przetwarzane",
                                "wrocław", "rozwój", "zespole", "umowę", "znajomości", "zatrudnienie", "rozwój", "osobowe", "stanowisku", "udział", "zespołu", "przygotowywanie", "przetwarzania", "wynagrodzenie",
                                "kwalifikacji", "umiejętności", "rachunkowości", "usługi", "działami", "for", "e", "nad", "ze", "an", "tym", "8", "także", "widziane", "dnido", "tym", "radom", "siedlce", 
                                "poznań", "panią", "pruszków", "płock", "mazowieckie", "usług", "obsługę", "zgodnie", "opiekę", "medyczną", "preferowane", "zespołem", "możliwością", "celów", "8", "3", "for",
                                "ustawy", "podobnym", "opportunities", "10", "także", "aplikacji", "dotyczących", "b", "zgody", "rekrutacji", "atrakcyjne", "wsparcie", "or", "osób", "nadzór", "sprzedaży",
                                "kontroli", "wykonywanie", "warunki", "narzędzi", "ostrołęka", "treści", "dofinansowanie", "klienta", "maszyn", "ekonomia", "realizowanych", "niezbędne", "przysługuje",
                                "bieżąca", "atmosferę", "badania", "sporządzania", "kontrola", "realizację", "ubezpieczenie", "analiz", "obsługa", "stanowisko", "klientami", "environment",
                                "warszawaradompłocksiedlcepruszkówostrołękakrakówłódźwrocław", "ds", "ms", "gc", "dan", "one", "alpro", "się",
                                "wfa", "czym", "będziesz", "odpowiedzialny", "ad", "hoc", "pod", "kątem", "nowych", "na", "tym", "stanowisku",
                                "będzie", "m.in", "ramach", "podstawie", "online", "rekrutacja", "h", "j", "c", "zaraz", "brutto", "euro", "udt", "zł", "nr", "etatu",
                                "zł", "zzp", "ul", "xi", "xii", "nawet", "depot", "emea", "bez", "NA", "oss", "y", "780zł", "30", "Opis", "stanowiska", 
                                "pracy", "opis", "en", "je", "20", "de", "1", "aby", "ich", "ciebie", "woj", "6", "kat", "een", "jak", "4",
                                "powiat", "stpr", "po", "van", "5", "ci", "00", "jeśli", "role", "twoich", "terenie", "innych", "są", "twoje",
                                "7", "op", "te", "jako", "11", "14", "które", "innymi", "naszych", "dnia", "chcesz", "np", "pracodawcykliknij",
                                "het", "cvsposób", "brakpozostałe", "konieczne:umiejętności", "wymagania:wykształcenie", "oferujemy:pracę",
                                "oferujemy:zatrudnienie", "pracępracę", "konieczne:umiejętności", "określonywymagane", "próbnywymagane",
                                "oferujemy:stabilne", "oferujemy:umowa", "oferujemy:umowę", "wymagania:doświadczenie", "pracęatrakcyjny",
                                "luxoft", "offer:a", "widziane:znajomość", "oferujemy:ciekawą", "12252", "oczekujemy:wykształcenia",
                                "oczekiwania:wykształcenie", "caremultikafeteria", "stanowiska:zapewnienie", "refundmultisportluxmed",
                                "insurancecommute", "skillsexcellent", "skillsstrong", "oferujemy:atrakcyjne", "próbnegoatrakcyjne",
                                "pracęwynagrodzenie", "heb", "sire", "brakmiejsce", "0px", "zawodowegopakiet", "technologycollaboration",
                                "skillsattractive", "programvarious", "environmentindividual", "activitiesbenefits:life", "teambuilding",
                                "dezynfekcjimożliwość", "mccormick", "pracowniczneśrodki", "wewnętrznerabaty", "legendary", "luxgood",
                                "couldn't", "pomorskierodzaj", "pracownicześrodki", "działaniajesteś", "technologiiwyzwania", "pracępakiet",
                                "sprzedażoweszkolenia", "premiowykonkursy", "pracypracę", "benefitówmaseczki", "sklepieobsługa", "realizacjipraca",
                                "premiijako", "klientamizdobywanie", "czynnościaktywna", "ciebie:umowa", "capgemini", "capgemini's", "myaudiobooks",
                                "medycznaubezpieczenie", "jeśli:masz", "wymagania:minimum", "stanowiska:praca", "pracęprywatna", "offer:employment",
                                "nicholas", "couldn't", "pko", "oferujemy:interesującą", "oczekujemy:wykształcenie", "zadania:zarządzanie",
                                "medycznadofinansowanie", "contractprivate", "jeśli:posiadasz", "pracęatrakcyjne", "zadania:realizacja",
                                "wymaganiawykształcenie", "oczekujemywykształcenia", "oferujemy:praca", "pracypakiet", "pracyatrakcyjne",
                                "wynagrodzeniemożliwość", "lotos", "carelife", "pracęmożliwość", "tram", "medycznakarta", "dobry:umowę",
                                "couldn't", "otrzymasz:stabilne", "widziane:doświadczenie", "offer:career", "ics", "oczekujemy:doświadczenia",
                                "grids", "brakpozostałe", "oczekujemy:minimum", "będzie:znajomość", "kandydata:wykształcenie", "skillsyou",
                                "zatrudnieniamożliwość", "thor", "employmentcompetitive", "dostajesz:stabilne", "ey", "biznesowychpodwyżki",
                                "biznesowychsamodzielnych", "awansusamodzielność", "multisportdofinansowanie", "team", "voor", "anesthesiemedewerker",
                                "działaniudoświadczonych", "stanowiska:obsługa", "stażowekompleksowy", "zależy.prywatną", "żyje.pełny",
                                "netherlands.the", "interesse", "deze", "bij", "przycisk", "aplikuj", "poznać", "szczegóły", "aplikowania",
                                "bezpośrednio", "zakres", "obowiązków", "warunek", "konieczny", "stanu", "preparatów", "otc", "prawidłowe",
                                "wysokiej", "wymagania:wykształcenia", "tj", "potwierdzających", "spełnienie", "ugruntowanej", "pozycji",
                                "spełnienie", "wymagania", "dynamicznie", "rozwijającej", "składania", "dokumentów", "jeśli:jesteś", "incl",
                                "samą", "231", "31", "22a", "bociana", "button", "apply", "190", "723", "niezbędnewykształcenie", "możesz", "liczyć", "należy", "złożyć", "wszystkie",
                                "formalności", "każdym", "etapie", "nasze", "oczekiwania", "główne", "zadania", "uur", "27", "kwietnia", "2016", "679",
                                "46", "95", "kontakt", "telefoniczny", "względzie", "oferta", "dotyczy", "akceptuje", "fakt",
                                "jij", "taak", "jouw", "uur.het", "36", "tot", "24", "ogłoszenia", "podgórne", "biskupice",
                                "zo", "mogelijk", "st", "16px", "height", "line", "13px", "size", "font", "family", "aria", "helvetica", "sans", "code",
                                "color", "li", "auto", "topmargin", "h2", "polskiegokorzystanie", "polskiegooświadczenie",
                                "warmińsko", "mazurskierodzaj", "opolskierodzaj", "podkarpackierodzaj", "lubelskierodzaj",
                                "podlaskierodzaj", "zachodniopomorskierodzaj", "osoba", "zatrudniona", "którym", "rozumiem",
                                "nasz", "klient", "danych.sposób", "initiatiefrijk.other", "konieczne:wykształcenie:zasadnicze", "data:stempla", "pocztowego", "numer", "referencyjny",
                                "zawierać", "powinny", "klauzulę", "zawodowegopozostałe", "om", "nauw", "udostępnienie", "moich",
                                "motywacyjnykopie", "list", "motywacyjny", "gdy", "znajdą", "upublicznienia", "datę", "typ", "adresowe", "margin", 
                                "top", "naszym", "poszukuje", "poszukujemy", "informujemy", "że", "er", "osoby",
                                "zainteresowane", "prosimy", "skarbowewymagania", "skarbowedokumenty",
                                "izba", "administracji", "skarbowej", "gronie", "najlepszych", "kandydatów",
                                "kandydatek", "pracodawcyadres", "dodania", "wakatdata", "zatrudnienia", "wskaźnik",
                                "bank", "nordea", "abp", "świętokrzyskiegorodzaj", "rodo", "oświadczam", "iż", "wyrażam", "zgodę",
                                "celem", "przeprowadzenia", "procedury", "komt.requirementsals", "sposób", "brak", "pracydoświadczenia",
                                "pracyniezbędnewykształcenie", "nieokreślonywymagane", "1wymagane", "świętokrzyskierodzaj", "lubuskierodzaj",
                                "adres", "als", "załadunek", "zespoledynamizm", "temat:struktury", "szukamy:studentów", "społecznejdobrej",
                                "rcsc", "posprzedażowejprzygotowanie", "officejęzyk", "myśleniadziałań", "jak:współpraca", "finansowychprowadzenia",
                                "finansowazbieranie", "bankowychwstępnej", "bankowychwstępna", "analitycznedyspozycyjnośćmile", "posprzedażowej",
                                "przygotowanie", "zajęćprzyjazną", "wymagania:absolwent", "a:status", "posprzedażowejprzygotowanie", "przenośnikowych",
                                "o.o", "enables", "12", "itp", "22", "naszego", "cię", "właśnie", "szczególności", "lubisz", "widziani",
                                "oferujemy", "jesteś", "poprzez", "osobą", "również", "wymiarze", "bądź", "pl", "oparciu", "inne", "met", 
                                "dodatkowe", "oparciu", "bądź", "dodatkowe", "resource", "ben", "door", "posprzedażowejprzygotowywanie",
                                "społecznejdobrej", "officejęzyk", "myśleniadziałań", "monitoringów", "bankowychwstępnej", "bankowychwstępna",
                                "analitycznedyspozycyjnośćmile", "mamy", "widziany", "warszawy", "200m", "100", "dziale", "pracownik", "f", "d", "ogólnoksztacce",
                                "gl", "ar", "ap", "couldn't", "firm's", "najmniej", "2021", "07", "rozumieniu", "przepisów", "kopia", "dokumentu", "potwierdzającego",
                                "osobistego", "dostarczenia", "publicznychnieskazanie", "miesiącu", "poprzedzającym", "publicznychoświadczenie",
                                "rehabilitacji", "branży", "papierniczej", "poszukuję", "kandydata", "światowego", "lidera", "umyślne", "przestępstwo",
                                "prawomocnym", "wyrokiem", "nieskazaniu", "pełni", "praw", "posiadaniu", "obywatelstwa", "skarbowe",
                                "zamierzających", "skorzystać", "doświadczenie", "zawodowe", "służbie", "cywilnej", "dyrektor",
                                "generalny", "zawodowegow", "stronie", "internetowej", "wymagane", "dokumenty", "być", "opatrzone",
                                "wzory", "oświadczeń", "urząd", "wojewódzki", "niepełnosprawnych", "wynosi", "muszą", "być", "opatrzone",
                                "własnoręcznie", "podpisane", "www", "gov", "zostaną", "komisyjnie", "monitorze", "ekranowym", "zniszczone",
                                "otoczenie", "organizacyjno", "dotyczące", "charakteru", "siedzibie", "urzędu", "godzin", "dziennie", "informacji",
                                "niejawnych", "zawodowego", "pozostałe", "pracyoświadczenie", "ochrony", "środowiska", "można",
                                "uzyskać", "składać", "przeprowadzenie", "postępowania", "sprawdzającego", "minimum", "średnie",
                                "która", "posiada", "oznaczonych", "klauzulą", "sposobu", "wykonywania", "informacje", "pracydokumenty",
                                "konkursy", "wewnętrzne", "administracyjnego", "kolejnego", "etapu", "wymagań", "formalnych", "rady",
                                "ministrów", "nadzoru", "budowlanego", "wysoko", "rozwinięte", "poświadczenia", "bezpieczeństwa",
                                "tłumacza", "przysięgłego", "wykształceniakopie", "przypadku", "środków", "powyżej", "urzędumiejsce",
                                "potrzeby", "miejsce", "czynności", "urzędzie", "21", "bip", "wykształceniakopie", "warszawie",
                                "ref", "prowadzi", "powyżej", "przed", "środków", "15", "stempla", "widziana", "budynek", "kopie",
                                "requirements", "ogłoszeniu", "możliwości", "czas", "naborze", "budynku", "formie", "terminie", 
                                "członkowie", "korpusu", "służby", "podpisem", "własnoręcznym", "wskazane", "niż", "poz", "423",
                                "513", "01", "nabory_waszawa", "ias", "elektroniczną", "pocztą", "wzór", "organami", "tymi",
                                "ogłoszenia", "nabór", "1997", "sierpnia", "wzór", "organami", "tymi", "2b", "felińskiego",
                                "pełniące", "funkcje", "publiczne", "zostanie", "uznana", "zakładu", "górniczego", "ograniczeniom",
                                "podlegają", "kolejowego", "wzór", "organami", "tymi", "biobójczych", "produktów", "dozorze",
                                "ruchu", "musi", "jednoznacznie", "wynikać", "starszy", "inspektor", "epuap", "ograniczeniu",
                                "niespełniająca", "wymogów", "w", "zakresie", "stanowiska", "pracy", "ogloszenia", "nabor",
                                "transportu", "drogowego", "1972", "000", "pln", "120", "90", "08", "dyrekcja", "generalna",
                                "klauzuli", "poufne", "dyrektora", "generalnego", "imię", "imiona", "including", "główny",
                                "powiatowy", "inspektorat", "mniejszości", "narodowych", "dróg", "motywacyjnym", "liście", "wojewódzka",
                                "komenda", "obrotu", "rocznego", "drogowych", "przebieg", "dotychczasowego", "naboru", "wyniki",
                                "zamieszkania", "miejscowość", "18budget", "zamknięty", "okres", "obiektów", "inżynierskich",
                                "offer", "rodzaj", "częste", "biggest", "glue", "katowiceremote", "expert", "zarządzania",
                                "kryzysowego", "possiblestart", "date", "postępowań", "administracyjnych", "contractgood",
                                "contract", "zielonej", "górze", "zakładach", "wykonujących", "roboty", "geologiczne",
                                "wszystkich", "wymaganych", "formalna", "weryfikacja", "oświadczenia", "składane", "adresem",
                                "80a", "poland", "adecco", "61", "501", "dolna", "wilda", "rozmowa", "kwalifikacyjna",
                                "przeciwdziałania", "przemocy", "zabytków", "nieruchomych", "specjalności", "górniczej",
                                "oświadczenia", "przedszkola", "tematyce", "związanej", "żywności", "netto", "balancevarious",
                                "belux", "developmentcompetitive", "covidwynagrodzenie", "devopswspółpraca", "pracyw", "110", "145", "jęz", "pomysłówrównowagę", "miedzy", "życiem", 
                                "19", "50", "zdrowotnekontrakt", "devopswynagrodzenie", "urlopoweoczekujemy", "warszawyprojekt",
                                "85", "80", "9", "dużej", "europejskiej", "firmy", "niemetodologia", "testngopracowywanie",
                                "podobnego", "pokrewnego", "obaszaru", "danychbardzo", "wymagańmonitorowanie", "konwersjiprzeprowadzanie", "frontendowychdoświadczenie", "automatycznychprzynajmniej",
                                "developerskimwykonywanie", "gitpoziom", "szkoleniapraca", "sukcesmożliwości", "całego", "przekroju",
                                "krytyczneanaliza", "narzędziprojektowanie", "środowiskukonkurencyjne", "seniortechnologie", "zdrowotnekontakt",
                                "podróżneubezpieczenie", "danychlokalizacja", "aplikacjibadanie", "alteryxwynagrodzenie", "publicznegowykorzystywane",
                                "warszawytesty", "hiszpania", "szwajcaria", "niemcy", "czechy", "polska", "nowej", "klientainterwencja",
                                "awswynagrodzenie", "awsznajomość", "healthlokalizacja", "dzięki", "aplikacjikontakt", "widoków",
                                "etatpłaską", "technologiamiprzyjazne", "bazyumiejętności", "szczególnym", "naciskiem", "całym", "tematem",
                                "systemuścisła", "myśleniadoświadczenie", "wykluczamy", "obecnie", "katowicach", "centreon",
                                "uop", "manualnychbardzo", "użytkownikawsparcie", "itpoziom", "automatycznychumiejętność", "wykorzystaniem",
                                "wykorzystywane", "widokow", "komponentów", "wspólnych", "szczególną", "dbałością", "rozwiązań", "obejmujące", "duży",
                                "potencjał", "obowiązki", "katowicachbranża", "przypadków", "ewentualnych", "lekkich",
                                "yue", "czasie", "rzeczywistym", "realizowany", "manualnych", "pomocą", "jednostkowych", "płatne", "dni",
                                "strukturę", "hmtl", "itprojekty", "rozwiązania", "wózka", "widłowego", "twój", "fundacji", "polski", "instytut",
                                "punktach", "dpd", "med", "proworkpl", "powierzonym", "regionie", "wózków", "widłowych", "wózkiem", "widłowym",
                                "kierowania", "wózkami", "trzeciak", "wózki", "widłowe", "na", "uniwersytet", "ekonomiczny"
                                ))

stop.words.ekonomia <- data.frame(word=c("księgowa", "księgowy"))
